### ISSUE TITLE
Zastic

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Snowflake-Coder-H2o/Blooket-Hack#11]
@ZasticBradyn Hey! Are you able to help me with something?

-Snow

**Comment by Hankypoo7** [comment]
Idk if he can but I can help you if you want

**Comment by ZasticBradyn** [comment]
> @ZasticBradyn Hey! Are you able to help me with something?
> 
> -Snow

Yeah sure, just add me on discord so we can talk!

zastix#0001
