### ISSUE TITLE
@ZasticBradyn 

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Snowflake-Coder-H2o/Blooket-Hack#14]
@ZasticBradyn Can you help me change the .LICENSE file to make it so no one can fork the repo, no one can copy our code without permission?

-Snow

**Comment by Hankypoo7** [comment]
i can try

**Comment by Hankypoo7** [comment]
fixed it now you have to have direct permission to fork it

**Comment by Snowflake-Coder-H2o** [comment]
ok Thanks!

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn Can you make sure thats right?

**Comment by ZasticBradyn** [comment]
lemme look

**Comment by ZasticBradyn** [comment]
yeah it looks good.
