### ISSUE TITLE
can i use your code

### ISSUE THREAD

**Issue by pazza223** [Snowflake-Coder-H2o/Blooket-Hack#2]
i am makeing a colection of blooket hacks all in one file for people to inport to google chrome. can i use your remove gliz watermark code?

**Comment by Snowflake-Coder-H2o** [comment]
Sure just give credit.

**Comment by pazza223** [comment]
i will

**Comment by Snowflake-Coder-H2o** [comment]
Ok!

-Snow

**Comment by pazza223** [comment]
also in the about, it seas
Q: Are you looking for people to help code?
A: RIght now, no. 
the I in Right shold not be capitalized. just leting you know.

**Comment by Snowflake-Coder-H2o** [comment]
@pazza223 Oh! Thanks for letting me know!

-Snow
