### ISSUE TITLE
hack menu has weird thing

### ISSUE THREAD

**Issue by RoronoaDLuffy** [Snowflake-Coder-H2o/Blooket-Hack#3]
![image](https://user-images.githubusercontent.com/87439474/156679705-e4af30d0-ba07-42bc-a44b-542ab4b9d3fb.png)

**Comment by Hankypoo7** [comment]
huh I can fix it

**Comment by Hankypoo7** [comment]
wait nvm it's blocked for some reason

**Comment by Snowflake-Coder-H2o** [comment]
@RoronoaDLuffy Sorry for the late response I was spending time with family, But please send a full screenshot! So I can guide you through it!


-Snow

**Comment by Snowflake-Coder-H2o** [comment]
@RoronoaDLuffy It's because it's either not the updated version of the hack menu or because you used the console. If it's the second one then you have to make a bookmark. but it might be both.
