### ISSUE TITLE
get crypto 

### ISSUE THREAD

**Issue by heeheeheehaaw** [Snowflake-Coder-H2o/Blooket-Hack#4]
get crypto almost got me in trobule i put 1k and it gave me 10 milion

**Comment by Snowflake-Coder-H2o** [comment]
@heeheeheehaaw yeah you have to watch out and make sure you have the right amount. 

-Snow

**Comment by heeheeheehaaw** [comment]
bru
![hqdefault](https://user-images.githubusercontent.com/98358829/157094419-1d17947a-437f-43d4-ab43-ada55fa11261.jpg)
