### ISSUE TITLE
Contact me please.

### ISSUE THREAD

**Issue by ZasticBradyn** [Snowflake-Coder-H2o/Blooket-Hack#6]
Hey, you have some pretty outdated stuff here, and your not using the new bypass for Alert(), Prompt() and Confirm(). If you have discord can you send it over?
Also, thanks for giving me credit.

my discord: zastix#0001

**Comment by Hankypoo7** [comment]
I dont have discord btw, and is there anyway me you and @Snowflake-Coder-H2o can prevent our accounts from getting banned, and what do those bypasses do?

**Comment by ZasticBradyn** [comment]
Alright thanks.

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn My discord Is my Github username. I just dont know what the 4 digits are. Im in school right now.
